// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany, CapabilityReference};
pub const CAPABILITY_ID: &str = "lenso.jobs@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const DESCRIPTOR_DIGEST: &str = "sha256:34fca9ad91952dd4eb9da844b94925cd0a54928843c803ed51e1c6ccb11d690d";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const JOBS_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const JOBS_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;
pub const JOBS_DESCRIPTOR_DIGEST: &str = DESCRIPTOR_DIGEST;
pub const JOBS_CONTRACT: CapabilityReference<JobsClient> = CapabilityReference::new(CAPABILITY_ID, DESCRIPTOR_VERSION, DESCRIPTOR_DIGEST);

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_jobs { () => { "{\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"claim\",\"complete\",\"enqueue\",\"fail\",\"inspect\",\"renew\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_jobs_client {
    () => { "{\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_optional_jobs_client {
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"optional\"}") };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_jobs_client {
    () => { "{\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" };
    ($requirement_id:literal) => { concat!("{\"requirement_id\":", stringify!($requirement_id), ",\"capability_id\":\"lenso.jobs@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}") };
}

pub const CLAIM_OPERATION: &str = "claim";
pub const COMPLETE_OPERATION: &str = "complete";
pub const ENQUEUE_OPERATION: &str = "enqueue";
pub const FAIL_OPERATION: &str = "fail";
pub const INSPECT_OPERATION: &str = "inspect";
pub const RENEW_OPERATION: &str = "renew";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimRequest {
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ClaimResponse {
    #[serde(rename = "attempt")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempt: i64,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "lease_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_expires_at: Timestamp,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

impl fmt::Debug for ClaimResponse {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ClaimResponse")
            .field("attempt", &self.attempt)
            .field("job_id", &self.job_id)
            .field("kind", &self.kind)
            .field("lease_expires_at", &self.lease_expires_at)
            .field("lease_token", &"<redacted>")
            .field("max_attempts", &self.max_attempts)
            .field("payload", &"<redacted>")
            .field("queue", &self.queue)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum ClaimError {
    InvalidQueue,
    NoJobAvailable,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
}

impl fmt::Debug for CompleteRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("CompleteRequest")
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CompleteResponse {
    #[serde(rename = "completed")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub completed: bool,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CompleteError {
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueRequest {
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Timestamp,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "payload")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub payload: std::collections::BTreeMap<String, serde_json::Value>,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
}

impl fmt::Debug for EnqueueRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("EnqueueRequest")
            .field("available_at", &self.available_at)
            .field("idempotency_key", &self.idempotency_key)
            .field("kind", &self.kind)
            .field("max_attempts", &self.max_attempts)
            .field("payload", &"<redacted>")
            .field("queue", &self.queue)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct EnqueueResponse {
    #[serde(rename = "created")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created: bool,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum EnqueueError {
    IdempotencyConflict,
    InvalidJob,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailRequest {
    #[serde(rename = "failure_code")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub failure_code: String,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
    #[serde(rename = "retryable")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub retryable: bool,
}

impl fmt::Debug for FailRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("FailRequest")
            .field("failure_code", &self.failure_code)
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .field("retryable", &self.retryable)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct FailResponse {
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Option<Timestamp>,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: FailResponseStatus,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum FailResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FailError {
    InvalidFailure,
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct InspectResponse {
    #[serde(rename = "attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub attempts: i64,
    #[serde(rename = "available_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub available_at: Timestamp,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub kind: String,
    #[serde(rename = "last_failure_code")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub last_failure_code: OptionalValue<String>,
    #[serde(rename = "lease_expires_at")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub lease_expires_at: OptionalValue<Timestamp>,
    #[serde(rename = "max_attempts")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub max_attempts: i64,
    #[serde(rename = "queue")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub queue: String,
    #[serde(rename = "status")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub status: InspectResponseStatus,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum InspectResponseStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "succeeded")]
    Succeeded,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InspectError {
    JobNotFound,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenewRequest {
    #[serde(rename = "job_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub job_id: String,
    #[serde(rename = "lease_token")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_token: String,
}

impl fmt::Debug for RenewRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RenewRequest")
            .field("job_id", &self.job_id)
            .field("lease_token", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RenewResponse {
    #[serde(rename = "lease_expires_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub lease_expires_at: Timestamp,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RenewError {
    InvalidLease,
    Unauthorized,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct JobsClaim;
impl RequestCapability for JobsClaim {
    type Request = ClaimRequest;
    type Response = ClaimResponse;
    type DomainError = ClaimError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CLAIM_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).claim(context, request)
    }
}

#[derive(Debug)]
pub struct JobsComplete;
impl RequestCapability for JobsComplete {
    type Request = CompleteRequest;
    type Response = CompleteResponse;
    type DomainError = CompleteError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != COMPLETE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).complete(context, request)
    }
}

#[derive(Debug)]
pub struct JobsEnqueue;
impl RequestCapability for JobsEnqueue {
    type Request = EnqueueRequest;
    type Response = EnqueueResponse;
    type DomainError = EnqueueError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != ENQUEUE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).enqueue(context, request)
    }
}

#[derive(Debug)]
pub struct JobsFail;
impl RequestCapability for JobsFail {
    type Request = FailRequest;
    type Response = FailResponse;
    type DomainError = FailError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != FAIL_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).fail(context, request)
    }
}

#[derive(Debug)]
pub struct JobsInspect;
impl RequestCapability for JobsInspect {
    type Request = InspectRequest;
    type Response = InspectResponse;
    type DomainError = InspectError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != INSPECT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).inspect(context, request)
    }
}

#[derive(Debug)]
pub struct JobsRenew;
impl RequestCapability for JobsRenew {
    type Request = RenewRequest;
    type Response = RenewResponse;
    type DomainError = RenewError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RENEW_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<JobsRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).renew(context, request)
    }
}

impl serde::Serialize for ClaimError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidQueue => serializer.serialize_str("invalid_queue"),
            Self::NoJobAvailable => serializer.serialize_str("no_job_available"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ClaimError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_queue" => Ok(Self::InvalidQueue),
                "no_job_available" => Ok(Self::NoJobAvailable),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for CompleteError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CompleteError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for EnqueueError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidJob => serializer.serialize_str("invalid_job"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for EnqueueError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_job" => Ok(Self::InvalidJob),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for FailError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidFailure => serializer.serialize_str("invalid_failure"),
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for FailError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_failure" => Ok(Self::InvalidFailure),
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for InspectError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::JobNotFound => serializer.serialize_str("job_not_found"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for InspectError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "job_not_found" => Ok(Self::JobNotFound),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RenewError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::InvalidLease => serializer.serialize_str("invalid_lease"),
            Self::Unauthorized => serializer.serialize_str("unauthorized"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RenewError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "invalid_lease" => Ok(Self::InvalidLease),
                "unauthorized" => Ok(Self::Unauthorized),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_claim_request(value: &ClaimRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_request(wire: &str) -> Result<ClaimRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_response(value: &ClaimResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_response(wire: &str) -> Result<ClaimResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_claim_error(value: &ClaimError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_claim_error(wire: &str) -> Result<ClaimError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_complete_request(value: &CompleteRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_request(wire: &str) -> Result<CompleteRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_response(value: &CompleteResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_response(wire: &str) -> Result<CompleteResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_complete_error(value: &CompleteError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_complete_error(wire: &str) -> Result<CompleteError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_enqueue_request(value: &EnqueueRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_request(wire: &str) -> Result<EnqueueRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_response(value: &EnqueueResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_response(wire: &str) -> Result<EnqueueResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_enqueue_error(value: &EnqueueError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_enqueue_error(wire: &str) -> Result<EnqueueError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_fail_request(value: &FailRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_request(wire: &str) -> Result<FailRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_response(value: &FailResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_response(wire: &str) -> Result<FailResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_fail_error(value: &FailError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_fail_error(wire: &str) -> Result<FailError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_inspect_request(value: &InspectRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_request(wire: &str) -> Result<InspectRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_response(value: &InspectResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_response(wire: &str) -> Result<InspectResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_inspect_error(value: &InspectError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_inspect_error(wire: &str) -> Result<InspectError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_renew_request(value: &RenewRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_request(wire: &str) -> Result<RenewRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_renew_response(value: &RenewResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_response(wire: &str) -> Result<RenewResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_renew_error(value: &RenewError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_renew_error(wire: &str) -> Result<RenewError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoJobsClaimResult {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure>;
}
impl __LensoIntoJobsClaimResult for Result<ClaimResponse, ClaimError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsClaimResult for Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsClaimResult for Result<ClaimResponse, lenso_plugin_authoring::PluginError<ClaimError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsClaimResult for Result<ClaimResponse, JobsClaimInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ClaimResponse, ClaimError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsClaimInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsClaimInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoJobsCompleteResult {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure>;
}
impl __LensoIntoJobsCompleteResult for Result<CompleteResponse, CompleteError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsCompleteResult for Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsCompleteResult for Result<CompleteResponse, lenso_plugin_authoring::PluginError<CompleteError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsCompleteResult for Result<CompleteResponse, JobsCompleteInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CompleteResponse, CompleteError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsCompleteInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsCompleteInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoJobsEnqueueResult {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure>;
}
impl __LensoIntoJobsEnqueueResult for Result<EnqueueResponse, EnqueueError> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsEnqueueResult for Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsEnqueueResult for Result<EnqueueResponse, lenso_plugin_authoring::PluginError<EnqueueError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsEnqueueResult for Result<EnqueueResponse, JobsEnqueueInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<EnqueueResponse, EnqueueError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsEnqueueInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsEnqueueInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoJobsFailResult {
    fn __lenso_into_result(self) -> Result<Result<FailResponse, FailError>, RuntimeFailure>;
}
impl __LensoIntoJobsFailResult for Result<FailResponse, FailError> {
    fn __lenso_into_result(self) -> Result<Result<FailResponse, FailError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsFailResult for Result<Result<FailResponse, FailError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<FailResponse, FailError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsFailResult for Result<FailResponse, lenso_plugin_authoring::PluginError<FailError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<FailResponse, FailError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsFailResult for Result<FailResponse, JobsFailInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<FailResponse, FailError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsFailInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsFailInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoJobsInspectResult {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure>;
}
impl __LensoIntoJobsInspectResult for Result<InspectResponse, InspectError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsInspectResult for Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsInspectResult for Result<InspectResponse, lenso_plugin_authoring::PluginError<InspectError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsInspectResult for Result<InspectResponse, JobsInspectInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<InspectResponse, InspectError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsInspectInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsInspectInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoJobsRenewResult {
    fn __lenso_into_result(self) -> Result<Result<RenewResponse, RenewError>, RuntimeFailure>;
}
impl __LensoIntoJobsRenewResult for Result<RenewResponse, RenewError> {
    fn __lenso_into_result(self) -> Result<Result<RenewResponse, RenewError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoJobsRenewResult for Result<Result<RenewResponse, RenewError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RenewResponse, RenewError>, RuntimeFailure> { self }
}
impl __LensoIntoJobsRenewResult for Result<RenewResponse, lenso_plugin_authoring::PluginError<RenewError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RenewResponse, RenewError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoJobsRenewResult for Result<RenewResponse, JobsRenewInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RenewResponse, RenewError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(JobsRenewInvocationError::Domain(error)) => Ok(Err(error)),
            Err(JobsRenewInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait JobsProvider: fmt::Debug + 'static {
    fn claim(&self, context: InvocationContext, request: ClaimRequest) -> NativeRequestFuture<JobsClaim>;
    fn complete(&self, context: InvocationContext, request: CompleteRequest) -> NativeRequestFuture<JobsComplete>;
    fn enqueue(&self, context: InvocationContext, request: EnqueueRequest) -> NativeRequestFuture<JobsEnqueue>;
    fn fail(&self, context: InvocationContext, request: FailRequest) -> NativeRequestFuture<JobsFail>;
    fn inspect(&self, context: InvocationContext, request: InspectRequest) -> NativeRequestFuture<JobsInspect>;
    fn renew(&self, context: InvocationContext, request: RenewRequest) -> NativeRequestFuture<JobsRenew>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_jobs {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportJobs;
        impl $crate::JobsProvider for $plugin {
        fn claim(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::ClaimRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsClaim> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::claim(&plugin, context, request).await;
                $crate::__LensoIntoJobsClaimResult::__lenso_into_result(result)
            })
        }
        fn complete(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::CompleteRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsComplete> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::complete(&plugin, context, request).await;
                $crate::__LensoIntoJobsCompleteResult::__lenso_into_result(result)
            })
        }
        fn enqueue(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::EnqueueRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsEnqueue> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::enqueue(&plugin, context, request).await;
                $crate::__LensoIntoJobsEnqueueResult::__lenso_into_result(result)
            })
        }
        fn fail(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::FailRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsFail> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::fail(&plugin, context, request).await;
                $crate::__LensoIntoJobsFailResult::__lenso_into_result(result)
            })
        }
        fn inspect(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsInspect> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::inspect(&plugin, context, request).await;
                $crate::__LensoIntoJobsInspectResult::__lenso_into_result(result)
            })
        }
        fn renew(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::RenewRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsRenew> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::renew(&plugin, context, request).await;
                $crate::__LensoIntoJobsRenewResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_object_jobs {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportJobs;
        impl $crate::JobsProvider for $object {
        fn claim(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::ClaimRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsClaim> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::claim(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsClaimResult::__lenso_into_result(result)
            })
        }
        fn complete(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::CompleteRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsComplete> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::complete(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsCompleteResult::__lenso_into_result(result)
            })
        }
        fn enqueue(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::EnqueueRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsEnqueue> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::enqueue(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsEnqueueResult::__lenso_into_result(result)
            })
        }
        fn fail(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::FailRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsFail> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::fail(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsFailResult::__lenso_into_result(result)
            })
        }
        fn inspect(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsInspect> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::inspect(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsInspectResult::__lenso_into_result(result)
            })
        }
        fn renew(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::RenewRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsRenew> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                let result = <$plugin>::renew(plugin.as_ref(), context, request).await;
                $crate::__LensoIntoJobsRenewResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_trait_object_jobs {
    ($object:ty, $plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportJobs;
        impl $crate::JobsProvider for $object {
        fn claim(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::ClaimRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsClaim> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::claim(plugin.as_ref(), context, request).await
            })
        }
        fn complete(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::CompleteRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsComplete> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::complete(plugin.as_ref(), context, request).await
            })
        }
        fn enqueue(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::EnqueueRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsEnqueue> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::enqueue(plugin.as_ref(), context, request).await
            })
        }
        fn fail(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::FailRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsFail> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::fail(plugin.as_ref(), context, request).await
            })
        }
        fn inspect(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::InspectRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsInspect> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::inspect(plugin.as_ref(), context, request).await
            })
        }
        fn renew(&self, context: __LensoNativeSupportJobs::InvocationContext, request: $crate::RenewRequest) -> __LensoNativeSupportJobs::NativeRequestFuture<$crate::JobsRenew> {
            let object = self.clone();
            ::std::boxed::Box::pin(async move {
                let plugin = object.get()?;
                <$plugin as $crate::JobsProvider>::renew(plugin.as_ref(), context, request).await
            })
        }
        }
    };
}

#[derive(Debug)]
struct JobsRequestEndpoint { provider: Rc<dyn JobsProvider> }

#[derive(Debug)]
pub struct JobsEndpoint<P: JobsProvider> { provider: Rc<P>, request_endpoint: JobsRequestEndpoint }
impl<P: JobsProvider> JobsEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn JobsProvider> = provider.clone();
        Self { provider, request_endpoint: JobsRequestEndpoint { provider: request_provider } }
    }
}

impl<P: JobsProvider> NativeRequestEndpoint for JobsEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CLAIM_OPERATION,
        COMPLETE_OPERATION,
        ENQUEUE_OPERATION,
        FAIL_OPERATION,
        INSPECT_OPERATION,
        RENEW_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CLAIM_OPERATION => {
                let Ok(request) = request.downcast::<ClaimRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).claim(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            COMPLETE_OPERATION => {
                let Ok(request) = request.downcast::<CompleteRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).complete(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            ENQUEUE_OPERATION => {
                let Ok(request) = request.downcast::<EnqueueRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).enqueue(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            FAIL_OPERATION => {
                let Ok(request) = request.downcast::<FailRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).fail(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            INSPECT_OPERATION => {
                let Ok(request) = request.downcast::<InspectRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).inspect(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RENEW_OPERATION => {
                let Ok(request) = request.downcast::<RenewRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).renew(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_jobs {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::JobsEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_jobs {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_jobs!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Clone, Debug)]
pub struct JobsClient {
    claim: NativeRequestHandle<JobsClaim>,
    complete: NativeRequestHandle<JobsComplete>,
    enqueue: NativeRequestHandle<JobsEnqueue>,
    fail: NativeRequestHandle<JobsFail>,
    inspect: NativeRequestHandle<JobsInspect>,
    renew: NativeRequestHandle<JobsRenew>,
}
impl JobsClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_requirement(dependencies, requirement_id)
    }

    pub async fn claim(&self, request: ClaimRequest) -> Result<ClaimResponse, JobsClaimInvocationError> {
        self.claim.invoke(CLAIM_OPERATION, request).await
            .map_err(JobsClaimInvocationError::Runtime)?
            .map_err(JobsClaimInvocationError::Domain)
    }

    pub async fn claim_with_context(&self, context: InvocationContext, request: ClaimRequest) -> Result<ClaimResponse, JobsClaimInvocationError> {
        self.claim.invoke_with_context(CLAIM_OPERATION, context, request).await
            .map_err(JobsClaimInvocationError::Runtime)?
            .map_err(JobsClaimInvocationError::Domain)
    }

    pub async fn complete(&self, request: CompleteRequest) -> Result<CompleteResponse, JobsCompleteInvocationError> {
        self.complete.invoke(COMPLETE_OPERATION, request).await
            .map_err(JobsCompleteInvocationError::Runtime)?
            .map_err(JobsCompleteInvocationError::Domain)
    }

    pub async fn complete_with_context(&self, context: InvocationContext, request: CompleteRequest) -> Result<CompleteResponse, JobsCompleteInvocationError> {
        self.complete.invoke_with_context(COMPLETE_OPERATION, context, request).await
            .map_err(JobsCompleteInvocationError::Runtime)?
            .map_err(JobsCompleteInvocationError::Domain)
    }

    pub async fn enqueue(&self, request: EnqueueRequest) -> Result<EnqueueResponse, JobsEnqueueInvocationError> {
        self.enqueue.invoke(ENQUEUE_OPERATION, request).await
            .map_err(JobsEnqueueInvocationError::Runtime)?
            .map_err(JobsEnqueueInvocationError::Domain)
    }

    pub async fn enqueue_with_context(&self, context: InvocationContext, request: EnqueueRequest) -> Result<EnqueueResponse, JobsEnqueueInvocationError> {
        self.enqueue.invoke_with_context(ENQUEUE_OPERATION, context, request).await
            .map_err(JobsEnqueueInvocationError::Runtime)?
            .map_err(JobsEnqueueInvocationError::Domain)
    }

    pub async fn fail(&self, request: FailRequest) -> Result<FailResponse, JobsFailInvocationError> {
        self.fail.invoke(FAIL_OPERATION, request).await
            .map_err(JobsFailInvocationError::Runtime)?
            .map_err(JobsFailInvocationError::Domain)
    }

    pub async fn fail_with_context(&self, context: InvocationContext, request: FailRequest) -> Result<FailResponse, JobsFailInvocationError> {
        self.fail.invoke_with_context(FAIL_OPERATION, context, request).await
            .map_err(JobsFailInvocationError::Runtime)?
            .map_err(JobsFailInvocationError::Domain)
    }

    pub async fn inspect(&self, request: InspectRequest) -> Result<InspectResponse, JobsInspectInvocationError> {
        self.inspect.invoke(INSPECT_OPERATION, request).await
            .map_err(JobsInspectInvocationError::Runtime)?
            .map_err(JobsInspectInvocationError::Domain)
    }

    pub async fn inspect_with_context(&self, context: InvocationContext, request: InspectRequest) -> Result<InspectResponse, JobsInspectInvocationError> {
        self.inspect.invoke_with_context(INSPECT_OPERATION, context, request).await
            .map_err(JobsInspectInvocationError::Runtime)?
            .map_err(JobsInspectInvocationError::Domain)
    }

    pub async fn renew(&self, request: RenewRequest) -> Result<RenewResponse, JobsRenewInvocationError> {
        self.renew.invoke(RENEW_OPERATION, request).await
            .map_err(JobsRenewInvocationError::Runtime)?
            .map_err(JobsRenewInvocationError::Domain)
    }

    pub async fn renew_with_context(&self, context: InvocationContext, request: RenewRequest) -> Result<RenewResponse, JobsRenewInvocationError> {
        self.renew.invoke_with_context(RENEW_OPERATION, context, request).await
            .map_err(JobsRenewInvocationError::Runtime)?
            .map_err(JobsRenewInvocationError::Domain)
    }
}

impl CapabilityClient for JobsClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            claim: dependencies.one::<JobsClaim>()?,
            complete: dependencies.one::<JobsComplete>()?,
            enqueue: dependencies.one::<JobsEnqueue>()?,
            fail: dependencies.one::<JobsFail>()?,
            inspect: dependencies.one::<JobsInspect>()?,
            renew: dependencies.one::<JobsRenew>()?,
        })
    }

    fn from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Self, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::from_dependencies(&dependencies)
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for JobsClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    claim: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsClaim>()?,
                    complete: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsComplete>()?,
                    enqueue: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsEnqueue>()?,
                    fail: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsFail>()?,
                    inspect: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsInspect>()?,
                    renew: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<JobsRenew>()?,
                    },
                ))
            })
            .collect()
    }

    fn many_from_requirement(
        dependencies: &PluginDependencies,
        requirement_id: &str,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        let dependencies = dependencies.requirement(requirement_id)?;
        Self::many_from_dependencies(&dependencies)
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum JobsClaimInvocationError {
    Domain(ClaimError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsCompleteInvocationError {
    Domain(CompleteError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsEnqueueInvocationError {
    Domain(EnqueueError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsFailInvocationError {
    Domain(FailError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsInspectInvocationError {
    Domain(InspectError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum JobsRenewInvocationError {
    Domain(RenewError),
    Runtime(RuntimeFailure),
}

#[derive(Clone, Copy, Debug)]
pub struct JobsGuestClient<'a, H: lenso_guest_sdk::HostImports> {
    capability: lenso_guest_sdk::GuestCapability<'a, H>,
}

impl<'a, H: lenso_guest_sdk::HostImports> JobsGuestClient<'a, H> {
    pub fn from_context(context: &'a lenso_guest_sdk::GuestContext<H>) -> Result<Self, lenso_guest_sdk::GuestError<serde_json::Value>> {
        context
            .require(CAPABILITY_ID, DESCRIPTOR_VERSION, &[CLAIM_OPERATION, COMPLETE_OPERATION, ENQUEUE_OPERATION, FAIL_OPERATION, INSPECT_OPERATION, RENEW_OPERATION], &[])
            .map(|capability| Self { capability })
    }

    pub fn claim(&self, request: &ClaimRequest) -> Result<ClaimResponse, lenso_guest_sdk::GuestError<ClaimError>> {
        self.capability.request(CLAIM_OPERATION, request)
    }

    pub fn complete(&self, request: &CompleteRequest) -> Result<CompleteResponse, lenso_guest_sdk::GuestError<CompleteError>> {
        self.capability.request(COMPLETE_OPERATION, request)
    }

    pub fn enqueue(&self, request: &EnqueueRequest) -> Result<EnqueueResponse, lenso_guest_sdk::GuestError<EnqueueError>> {
        self.capability.request(ENQUEUE_OPERATION, request)
    }

    pub fn fail(&self, request: &FailRequest) -> Result<FailResponse, lenso_guest_sdk::GuestError<FailError>> {
        self.capability.request(FAIL_OPERATION, request)
    }

    pub fn inspect(&self, request: &InspectRequest) -> Result<InspectResponse, lenso_guest_sdk::GuestError<InspectError>> {
        self.capability.request(INSPECT_OPERATION, request)
    }

    pub fn renew(&self, request: &RenewRequest) -> Result<RenewResponse, lenso_guest_sdk::GuestError<RenewError>> {
        self.capability.request(RENEW_OPERATION, request)
    }
}

#[derive(Debug, Default)]
pub struct JobsJsonCodec;

impl lenso_runtime_codec::JsonCapabilityCodec for JobsJsonCodec {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }

    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }

    fn descriptor_digest(&self) -> &'static str { DESCRIPTOR_DIGEST }

    fn request_operations(&self) -> &'static [&'static str] { &[CLAIM_OPERATION, COMPLETE_OPERATION, ENQUEUE_OPERATION, FAIL_OPERATION, INSPECT_OPERATION, RENEW_OPERATION] }
    fn stream_operations(&self) -> &'static [&'static str] { &[] }

    fn encode_request(&self, operation: &str, request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        match operation {
            CLAIM_OPERATION => {
                let value = request.downcast_ref::<ClaimRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            COMPLETE_OPERATION => {
                let value = request.downcast_ref::<CompleteRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            ENQUEUE_OPERATION => {
                let value = request.downcast_ref::<EnqueueRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            FAIL_OPERATION => {
                let value = request.downcast_ref::<FailRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            INSPECT_OPERATION => {
                let value = request.downcast_ref::<InspectRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            RENEW_OPERATION => {
                let value = request.downcast_ref::<RenewRequest>().ok_or_else(runtime_codec_protocol_failure)?;
                serde_json::to_value(value).map_err(|_| runtime_codec_protocol_failure())
            },
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_response(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CLAIM_OPERATION => serde_json::from_value::<ClaimResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            COMPLETE_OPERATION => serde_json::from_value::<CompleteResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            ENQUEUE_OPERATION => serde_json::from_value::<EnqueueResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            FAIL_OPERATION => serde_json::from_value::<FailResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INSPECT_OPERATION => serde_json::from_value::<InspectResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RENEW_OPERATION => serde_json::from_value::<RenewResponse>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn decode_domain_error(&self, operation: &str, value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        match operation {
            CLAIM_OPERATION => serde_json::from_value::<ClaimError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            COMPLETE_OPERATION => serde_json::from_value::<CompleteError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            ENQUEUE_OPERATION => serde_json::from_value::<EnqueueError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            FAIL_OPERATION => serde_json::from_value::<FailError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            INSPECT_OPERATION => serde_json::from_value::<InspectError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            RENEW_OPERATION => serde_json::from_value::<RenewError>(value)
                .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                .map_err(|_| runtime_codec_protocol_failure()),
            _ => Err(runtime_codec_unknown_operation(operation)),
        }
    }

    fn encode_stream_open(&self, operation: &str, _request: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn encode_stream_message(&self, operation: &str, _message: &dyn std::any::Any) -> Result<serde_json::Value, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_message(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn decode_stream_domain_error(&self, operation: &str, _value: serde_json::Value) -> Result<Box<dyn std::any::Any>, RuntimeFailure> {
        Err(runtime_codec_unknown_operation(operation))
    }

    fn invoke_host_request(&self, dependency: lenso_kernel::PluginDependencyHandle, operation: String, request: serde_json::Value, context: InvocationContext) -> lenso_runtime_codec::JsonHostRequestFuture {
        match operation.as_str() {
            CLAIM_OPERATION => {
                let request = serde_json::from_value::<ClaimRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsClaim>()?;
                    match handle.invoke_with_context(CLAIM_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            COMPLETE_OPERATION => {
                let request = serde_json::from_value::<CompleteRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsComplete>()?;
                    match handle.invoke_with_context(COMPLETE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            ENQUEUE_OPERATION => {
                let request = serde_json::from_value::<EnqueueRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsEnqueue>()?;
                    match handle.invoke_with_context(ENQUEUE_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            FAIL_OPERATION => {
                let request = serde_json::from_value::<FailRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsFail>()?;
                    match handle.invoke_with_context(FAIL_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            INSPECT_OPERATION => {
                let request = serde_json::from_value::<InspectRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsInspect>()?;
                    match handle.invoke_with_context(INSPECT_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            RENEW_OPERATION => {
                let request = serde_json::from_value::<RenewRequest>(request).map_err(|_| runtime_codec_protocol_failure());
                Box::pin(async move {
                    let request = request?;
                    let handle = dependency.typed::<JobsRenew>()?;
                    match handle.invoke_with_context(RENEW_OPERATION, context, request).await? {
                        Ok(response) => serde_json::to_value(response)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::Success)
                            .map_err(|_| runtime_codec_protocol_failure()),
                        Err(error) => serde_json::to_value(error)
                            .map(lenso_runtime_codec::JsonInvocationOutcome::DomainError)
                            .map_err(|_| runtime_codec_protocol_failure()),
                    }
                })
            },
            _ => Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation)))),
        }
    }

    fn open_host_stream(&self, _dependency: lenso_kernel::PluginStreamDependencyHandle, operation: String, _request: serde_json::Value, _context: InvocationContext) -> lenso_runtime_codec::JsonHostStreamOpenFuture {
        Box::pin(std::future::ready(Err(runtime_codec_unknown_operation(&operation))))
    }
}

fn runtime_codec_protocol_failure() -> RuntimeFailure { RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID } }

fn runtime_codec_unknown_operation(operation: &str) -> RuntimeFailure {
    RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }
}
